from django.db import models

class Multa(models.Model):
    data_inversa = models.DateField()
    dia_semana = models.CharField(max_length=20)
    horario = models.TimeField()
    uf = models.CharField(max_length=2)
    br = models.IntegerField()
    km = models.DecimalField(max_digits=8, decimal_places=1)
    municipio = models.CharField(max_length=100)
    causa_acidente = models.CharField(max_length=100)
    tipo_acidente = models.CharField(max_length=100)
    classificacao_acidente = models.CharField(max_length=100)
    fase_dia = models.CharField(max_length=100)
    sentido_via = models.CharField(max_length=100)
    condicao_metereologica = models.CharField(max_length=100)
    tipo_pista = models.CharField(max_length=100)
    tracado_via = models.CharField(max_length=100)
    uso_solo = models.CharField(max_length=100)
    pessoas = models.IntegerField()
    mortos = models.IntegerField()
    feridos_leves = models.IntegerField()
    feridos_graves = models.IntegerField()
    ilesos = models.IntegerField()
    ignorados = models.IntegerField()
    feridos = models.IntegerField()
    veiculos = models.IntegerField()
    latitude = models.DecimalField(max_digits=11, decimal_places=8)
    longitude = models.DecimalField(max_digits=11, decimal_places=8)
    regional = models.CharField(max_length=100)
    delegacia = models.CharField(max_length=100)
    uop = models.CharField(max_length=100)
